/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [ 
    './index.html', 
    './src/**/*.{js,ts,jsx,tsx}', 
  ],
  darkMode: ["selector", "&:is(.dark *)"],
  theme: {
    extend: {
      boxShadow: {
        '3xl': '0 35px 60px -15px rgba(0, 0, 0, 0.5)',
        '4xl': '0 45px 80px -20px rgba(0, 0, 0, 0.6)',
        'soft-glow': '0 0 50px rgba(100, 100, 255, 0.3)',
        'glow-primary': '0 0 20px oklch(0.65 0.25 220 / 0.3)',
        'glow-accent': '0 0 20px oklch(0.70 0.20 200 / 0.3)',
      },
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        border: "var(--border)",
        input: {
          DEFAULT: "var(--input)",
          background: "var(--input-background)",
        },
        switch: {
          background: "var(--switch-background)",
        },
        ring: "var(--ring)",
        chart: {
          "1": "var(--chart-1)",
          "2": "var(--chart-2)",
          "3": "var(--chart-3)",
          "4": "var(--chart-4)",
          "5": "var(--chart-5)",
        },
        sidebar: {
          DEFAULT: "var(--sidebar)",
          foreground: "var(--sidebar-foreground)",
          primary: "var(--sidebar-primary)",
          "primary-foreground": "var(--sidebar-primary-foreground)",
          accent: "var(--sidebar-accent)",
          "accent-foreground": "var(--sidebar-accent-foreground)",
          border: "var(--sidebar-border)",
          ring: "var(--sidebar-ring)",
        },
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius)",
        xl: "var(--radius-xl)",
      },
      fontSize: {
        base: "var(--text-base)",
        xs: 'var(--text-xs)',
        sm: 'var(--text-sm)',
        lg: 'var(--text-lg)',
        xl: 'var(--text-xl)',
        '2xl': 'var(--text-2xl)',
        '3xl': 'var(--text-3xl)',
        '4xl': 'var(--text-4xl)',
      },
      fontWeight: {
        normal: "var(--font-weight-normal)",
        medium: "var(--font-weight-medium)",
      },
      backgroundImage: {
        'gradient-primary': 'linear-gradient(135deg, oklch(0.65 0.25 220), oklch(0.70 0.20 200))',
        'gradient-secondary': 'linear-gradient(135deg, oklch(0.60 0.22 280), oklch(0.65 0.18 300))',
        'gradient-accent': 'linear-gradient(135deg, oklch(0.65 0.25 200), oklch(0.70 0.20 180))',
        'gradient-dark-card': 'linear-gradient(135deg, oklch(0.12 0.015 240), oklch(0.15 0.02 250))',
        'gradient-dark-bg': 'linear-gradient(135deg, oklch(0.08 0.02 240), oklch(0.10 0.015 250))',
        'text-gradient-primary': 'linear-gradient(135deg, oklch(0.75 0.25 220), oklch(0.80 0.20 200))',
        'text-gradient-secondary': 'linear-gradient(135deg, oklch(0.70 0.22 280), oklch(0.75 0.18 300))',
        'text-gradient-accent': 'linear-gradient(135deg, oklch(0.75 0.25 200), oklch(0.80 0.20 180))',
      },
    },
  },
  plugins: [
    function ({ addUtilities, addBase, theme }) {
      addUtilities({
        ".outline-ring\\/50": {
          "box-shadow": "0 0 0 3px transparent",
        },
        ".bg-muted\\/30": {
          "background-color": "color-mix(in oklab, var(--muted) 30%, transparent)",
        },
        ".gradient-primary": {
          "background": "linear-gradient(135deg, oklch(0.65 0.25 220), oklch(0.70 0.20 200))",
        },
        ".gradient-secondary": {
          "background": "linear-gradient(135deg, oklch(0.60 0.22 280), oklch(0.65 0.18 300))",
        },
        ".gradient-accent": {
          "background": "linear-gradient(135deg, oklch(0.65 0.25 200), oklch(0.70 0.20 180))",
        },
        ".gradient-dark-card": {
          "background": "linear-gradient(135deg, oklch(0.12 0.015 240), oklch(0.15 0.02 250))",
        },
        ".gradient-dark-bg": {
          "background": "linear-gradient(135deg, oklch(0.08 0.02 240), oklch(0.10 0.015 250))",
        },
        ".text-gradient-primary": {
          "background": "linear-gradient(135deg, oklch(0.75 0.25 220), oklch(0.80 0.20 200))",
          "-webkit-background-clip": "text",
          "-webkit-text-fill-color": "transparent",
          "background-clip": "text",
        },
        ".text-gradient-secondary": {
          "background": "linear-gradient(135deg, oklch(0.70 0.22 280), oklch(0.75 0.18 300))",
          "-webkit-background-clip": "text",
          "-webkit-text-fill-color": "transparent",
          "background-clip": "text",
        },
        ".text-gradient-accent": {
          "background": "linear-gradient(135deg, oklch(0.75 0.25 200), oklch(0.80 0.20 180))",
          "-webkit-background-clip": "text",
          "-webkit-text-fill-color": "transparent",
          "background-clip": "text",
        },
        ".glow-primary": {
          "box-shadow": "0 0 20px oklch(0.65 0.25 220 / 0.3)",
        },
        ".glow-accent": {
          "box-shadow": "0 0 20px oklch(0.70 0.20 200 / 0.3)",
        },
        ".border-gradient": {
          "position": "relative",
        },
        ".border-gradient::before": {
          "content": "''",
          "position": "absolute",
          "inset": "0",
          "padding": "1px",
          "background": "linear-gradient(135deg, oklch(0.65 0.25 220), oklch(0.70 0.20 200))",
          "border-radius": "inherit",
          "mask": "linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0)",
          "mask-composite": "exclude",
        },
      }, {
        variants: ["responsive", "hover"],
        layer: "utilities",
      });
      addBase({
        ":root": {
          "--font-size": "14px",
          "--radius": "0.625rem",
          "--radius-sm": "calc(var(--radius) - 4px)",
          "--radius-md": "calc(var(--radius) - 2px)",
          "--radius-lg": "var(--radius)",
          "--radius-xl": "calc(var(--radius) + 4px)",
          "--background": "oklch(1 0 0)",
          "--foreground": "oklch(0.145 0 0)",
          "--card": "oklch(1 0 0)",
          "--card-foreground": "oklch(0.145 0 0)",
          "--popover": "oklch(1 0 0)",
          "--popover-foreground": "oklch(0.145 0 0)",
          "--primary": "oklch(0.205 0 0)",
          "--primary-foreground": "oklch(0.985 0 0)",
          "--secondary": "oklch(0.97 0 0)",
          "--secondary-foreground": "oklch(0.205 0 0)",
          "--muted": "oklch(0.97 0 0)",
          "--muted-foreground": "oklch(0.556 0 0)",
          "--accent": "oklch(0.97 0 0)",
          "--accent-foreground": "oklch(0.205 0 0)",
          "--destructive": "oklch(0.577 0.245 27.325)",
          "--destructive-foreground": "oklch(0.577 0.245 27.325)",
          "--border": "oklch(0.922 0 0)",
          "--input": "oklch(0.922 0 0)",
          "--input-background": "#f3f3f5",
          "--switch-background": "#cbced4",
          "--ring": "oklch(0.708 0 0)",
          "--chart-1": "oklch(0.646 0.222 41.116)",
          "--chart-2": "oklch(0.6 0.118 184.704)",
          "--chart-3": "oklch(0.398 0.07 227.392)",
          "--chart-4": "oklch(0.828 0.189 84.429)",
          "--chart-5": "oklch(0.769 0.188 70.08)",
          "--sidebar": "oklch(0.985 0 0)",
          "--sidebar-foreground": "oklch(0.145 0 0)",
          "--sidebar-primary": "oklch(0.205 0 0)",
          "--sidebar-primary-foreground": "oklch(0.985 0 0)",
          "--sidebar-accent": "oklch(0.97 0 0)",
          "--sidebar-accent-foreground": "oklch(0.205 0 0)",
          "--sidebar-border": "oklch(0.922 0 0)",
          "--sidebar-ring": "oklch(0.708 0 0)",
        },
        ".dark": {
          "--background": "oklch(0.08 0.02 240)",
          "--foreground": "oklch(0.98 0.005 240)",
          "--card": "oklch(0.12 0.015 240)",
          "--card-foreground": "oklch(0.95 0.005 240)",
          "--popover": "oklch(0.12 0.015 240)",
          "--popover-foreground": "oklch(0.95 0.005 240)",
          "--primary": "oklch(0.65 0.25 220)",
          "--primary-foreground": "oklch(0.98 0.005 240)",
          "--secondary": "oklch(0.18 0.02 280)",
          "--secondary-foreground": "oklch(0.90 0.01 240)",
          "--muted": "oklch(0.15 0.02 250)",
          "--muted-foreground": "oklch(0.65 0.01 240)",
          "--accent": "oklch(0.20 0.03 200)",
          "--accent-foreground": "oklch(0.95 0.01 200)",
          "--destructive": "oklch(0.55 0.22 15)",
          "--destructive-foreground": "oklch(0.95 0.01 15)",
          "--border": "oklch(0.25 0.02 240)",
          "--input": "oklch(0.16 0.02 240)",
          "--ring": "oklch(0.65 0.25 220)",
          "--chart-1": "oklch(0.65 0.25 220)",
          "--chart-2": "oklch(0.70 0.20 160)",
          "--chart-3": "oklch(0.75 0.18 60)",
          "--chart-4": "oklch(0.68 0.22 300)",
          "--chart-5": "oklch(0.72 0.20 20)",
          "--sidebar": "oklch(0.10 0.02 240)",
          "--sidebar-foreground": "oklch(0.95 0.005 240)",
          "--sidebar-primary": "oklch(0.65 0.25 220)",
          "--sidebar-primary-foreground": "oklch(0.98 0.005 240)",
          "--sidebar-accent": "oklch(0.16 0.02 240)",
          "--sidebar-accent-foreground": "oklch(0.90 0.01 240)",
          "--sidebar-border": "oklch(0.22 0.02 240)",
          "--sidebar-ring": "oklch(0.65 0.25 220)",
        },
        html: {
          "font-size": "var(--font-size)",
        },
        ":where(:not(:has([class*=' text-']), :not(:has([class^='text-']))))": {
          h1: {
            "font-size": "var(--text-2xl)",
            "font-weight": "var(--font-weight-medium)",
            "line-height": "1.5",
          },
          h2: {
            "font-size": "var(--text-xl)",
            "font-weight": "var(--font-weight-medium)",
            "line-height": "1.5",
          },
          h3: {
            "font-size": "var(--text-lg)",
            "font-weight": "var(--font-weight-medium)",
            "line-height": "1.5",
          },
          h4: {
            "font-size": "var(--text-base)",
            "font-weight": "var(--font-weight-medium)",
            "line-height": "1.5",
          },
          p: {
            "font-size": "var(--text-base)",
            "font-weight": "var(--font-weight-normal)",
            "line-height": "1.5",
          },
          label: {
            "font-size": "var(--text-base)",
            "font-weight": "var(--font-weight-medium)",
            "line-height": "1.5",
          },
          button: {
            "font-size": "var(--text-base)",
            "font-weight": "var(--font-weight-medium)",
            "line-height": "1.5",
          },
          input: {
            "font-size": "var(--text-base)",
            "font-weight": "var(--font-weight-normal)",
            "line-height": "1.5",
          },
        },
      });
    },
  ],
};